name: iOS Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Test
        uses: sersoft-gmbh/xcodebuild-action@v3.2.0
        with:
          project: EPCollaboratif.xcodeproj
          scheme: EPCollaboratif
          destination: 'platform=iOS Simulator, name=iPhone 14'
          action: test
          result-bundle-path: 'TestResults/TestResults.xcresult'
          
     - name: Process Test Results
       uses: kishikawakatsumi/xcresulttool@v1
       with:
           path: TestResults/TestResults.xcresult
           if: success() || failure()
     
